

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Do the build"
    - bash: echo  $(newveriable)
    - bash: echo  $(calss)
    - bash:  ls -R $(Build.ArtifactStagingDirectory)

